singleTypes:
    - id: post
      directory: /content/
      fileName: home

repeatableTypes:
    - id: post
      directory: /content/post/
      fileExtension: md
    - id: gallery
      directory: /content/gallery/
